[package]
name = "webrtc-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
webrtc = "0.9"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.20"
futures-util = "0.3"
log = "0.4"
env_logger = "0.10"
serde_json = "1.0"



